#!/bin/sh

# IN ORDER FOR THIS TO WORK IT *MAY* BE NECESSARY TO 
# DISABLE BROWSER CACHING (true for brave; not true for qutebrowser)

# meant to toggle blocking and unblocking social network websites
# must be run as superuser

# checks if websites are blocked in /etc/hosts
# and toggles between blocked and unblocked

# it's very ad hoc and made to suit my own configuration
# and must be manually changed should my /etc/hosts change

START=12
STOP=74

FIRSTLINE="1q;d"

if [ "$(sed "1q;d" /etc/hosts | cut -d'=' -f1)" != "# SOCBLOC_STATUS" ] ; then
       sed -i "1s/^/\# SOCBLOC_STATUS=OFF\n\0/" /etc/hosts
fi

STATUS=$(sed $FIRSTLINE /etc/hosts | cut -d'=' -f2)  #checks the status 	

if [ "$STATUS" = "ON" ]; then
 	sed -i --expression "${START},${STOP}s/^#//" \
	       --expression "1s/ON/OFF/"  /etc/hosts 	

elif [ "$STATUS" = "OFF" ]; then
 	sed -i --expression "${START},${STOP}s/^/#/" \
	       --expression "1s/OFF/ON/"  /etc/hosts 	
fi

